<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro"  name="robot">

    <!-- See common Gazebo pugins in the world file -->
    
    <!--
        To re-generate robot.urdf.generated.xml manually for troubleshooting:
          cd ~/robot_ws
          colcon build
          xacro install/articubot_one/share/articubot_one/robots/seggy/description/robot.urdf.xacro sim_mode:=false > src/articubot_one/robots/seggy/description/robot.urdf.generated.xml
    -->

    <xacro:include filename="../../../description/common_properties.xacro" />

    <xacro:include filename="robot_core.xacro" />

    <xacro:property name="imu_offset_x" value="${wheel_offset_x + 0.09}"/>
    <xacro:property name="imu_offset_z" value="0.1"/>
    <xacro:property name="imu_visual_size" value="0.01"/>
    <xacro:include filename="../../../description/imu.xacro" />

    <xacro:include filename="../../../description/magnetometer.xacro" />

    <xacro:property name="laser_offset_x" value="${wheel_offset_x + 0.05}"/>
    <xacro:property name="laser_offset_z" value="0.27"/>
    <xacro:include filename="../../../description/lidar.xacro" />

    <xacro:property name="open_circuit_voltage" value="12.592"/>
    <xacro:property name="battery_capacity" value="20.0"/>
    <xacro:include filename="../../../description/battery.xacro" />

    <xacro:property name="depth_camera_offset_x" value="${wheel_offset_x}"/>
    <xacro:property name="depth_camera_offset_z" value="${chassis_top_offset + 0.12}"/>
    <xacro:include filename="../../../description/depth_camera.xacro"/>

    <xacro:unless value="$(arg sim_mode)">
        <xacro:arg name="parent_frame" default="depth_camera_link_optical" />
        <xacro:include filename="$(find depthai_descriptions)/urdf/depthai_descr.urdf.xacro"/>
    </xacro:unless>
    
    <xacro:include filename="ros2_control.xacro" />

</robot>