<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro"  name="robot">

    <!-- See common Gazebo pugins in the world file -->
    
    <!--
        To re-generate robot.urdf.generated.xml manually for troubleshooting:
          cd ~/robot_ws
          colcon build
          xacro install/articubot_one/share/articubot_one/robots/plucky/description/robot.urdf.xacro sim_mode:=false > src/articubot_one/robots/plucky/description/robot.urdf.generated.xml
    -->

    <xacro:include filename="../../../description/common_properties.xacro" />

    <xacro:include filename="robot_core.xacro" />

    <xacro:property name="imu_offset_x" value="${wheel_offset_x + 0.09}"/>
    <xacro:property name="imu_offset_z" value="0.1"/>
    <xacro:property name="imu_visual_size" value="0.01"/>
    <xacro:include filename="../../../description/imu.xacro" />

    <xacro:include filename="../../../description/magnetometer.xacro" />

    <!-- using arguments here, as that allows overriding default values -->
    <xacro:arg name="lidar_offset_x" default="${wheel_offset_x}"/>
    <xacro:arg name="lidar_offset_z" default="0.47"/>
    <xacro:arg name="lidar_base_length" default="0.01"/>
    <xacro:include filename="../../../description/lidar.xacro" />

    <xacro:property name="sonars_offset_x" value="${chassis_length/2 + 0.005}"/>
    <xacro:property name="sonars_offset_y" value="${chassis_width/2 - 0.02}"/>
    <xacro:property name="sonars_offset_z" value="0.05"/>
    <xacro:include filename="../../../description/sonars.xacro" />

    <xacro:property name="gps_offset_x" value="${wheel_offset_x}"/>
    <xacro:property name="gps_offset_y" value="-0.16"/>
    <xacro:property name="gps_offset_z" value="0.45"/>
    <xacro:include filename="../../../description/gps.xacro" />

    <xacro:property name="camera_offset_x" value="${wheel_offset_x + 0.1}"/>
    <xacro:property name="camera_offset_z" value="0.25"/>
    <xacro:include filename="../../../description/camera.xacro" />

    <xacro:property name="open_circuit_voltage" value="12.592"/>
    <xacro:property name="battery_capacity" value="20.0"/>
    <xacro:include filename="../../../description/battery.xacro" />

    <xacro:property name="depth_camera_offset_x" value="${wheel_offset_x + 0.045}"/>
    <xacro:property name="depth_camera_offset_z" value="0.4"/>
    <xacro:include filename="../../../description/depth_camera.xacro"/>

    <xacro:unless value="$(arg sim_mode)">
        <xacro:arg name="parent_frame" default="depth_camera_link_optical" />
        <xacro:include filename="$(find depthai_descriptions)/urdf/depthai_descr.urdf.xacro"/>
    </xacro:unless>
    
    <xacro:include filename="ros2_control.xacro" />

</robot>