<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro"  name="robot">

    <!-- robot.urdf.xacro
    imports 
        robot_core.xacro
        common_properties.xacro
        individual sensors - each with their positions
            ydlidar.xacro
            JP_imu.xacro
            fisheye_camera.xacro
            OAK-D camera
            battery.xacro
            ros2_control.xacro   
    -->
   
    <!-- See common Gazebo pugins in the world file -->
    <!--
        To re-generate robot.urdf.generated.xml manually for troubleshooting:
          cd ~/robot_ws
          colcon build
          xacro install/articubot_one/share/articubot_one/robots/stingray/description/robot.urdf.xacro sim_mode:=false > src/articubot_one/robots/stingray/description/robot.urdf.generated.xml
    -->
    <!-- COMMON -->
    <xacro:include filename="$(find articubot_one)/description/common_properties.xacro" />

    <!-- CORE -->
    <xacro:include filename="robot_core.xacro" />

    <!-- USB FISHEYE CAMERA -->
    <!-- 
    <xacro:property name="camera_offset_x" value="${front_panel_offset}"/>
    <xacro:property name="camera_offset_z" value="0.01525"/>
    <xacro:include filename="$(find articubot_one)/robots/stingray/description/fisheye_camera.xacro" />
    <xacro:property name="camera_rotation_y" value="-0.1571"/>    =9 degrees 
    -->

    <!-- YDLIDAR  -->
    <!-- <xacro:property name="ydlidar_support_offset_x" value="0.042"/>
    <xacro:property name="ydlidar_support_offset_y" value="-0.02"/>
    <xacro:property name="ydlidar_support_offset_z" value="${chassis_height/2 + 0.00375}"/>
    <xacro:include filename="$(find articubot_one)/robots/stingray/description/ydlidar_support.xacro"/>
    <xacro:include filename="$(find articubot_one)/robots/stingray/description/ydlidar.xacro" /> -->

    <!-- LDLIDAR LD19 -->
    <xacro:property name="ldlidar_support_offset_x" value="0.04669"/>
    <xacro:property name="ldlidar_support_offset_y" value="0.0"/>
    <xacro:property name="ldlidar_support_offset_z" value="${chassis_height/2}"/>
    <xacro:include filename="$(find articubot_one)/robots/stingray/description/ldlidar_support.xacro"/>
    <xacro:include filename="$(find articubot_one)/robots/stingray/description/ldlidar.xacro"/>

    <!-- IMU -->
    <!-- BNO055 IMU is placed at the center of the wheel axis = base_link -->
    <xacro:property name="imu_offset_x" value="0.0"/>
    <xacro:property name="imu_offset_y" value="0.0"/>
    <xacro:property name="imu_offset_z" value="0.0"/>
    <xacro:property name="imu_rotation_x" value="0.0"/>
    <xacro:property name="imu_rotation_y" value="0.0"/>
    <xacro:property name="imu_rotation_z" value="0.0"/>
    <xacro:include filename="$(find articubot_one)/robots/stingray/description/BNO055_imu.xacro"/>

    <!-- BATTERY -->
    <xacro:include filename="$(find articubot_one)/robots/stingray/description/Zeee_LiPo_battery.xacro" />

    <!-- OAK-D Camera -->
    <xacro:include filename="$(find articubot_one)/robots/stingray/description/oakd.xacro" />
    <xacro:oakd_link mount_point="front_panel"/>
   <xacro:oakd_joint x="0.023" y="0.01" z="0.030" roll="0" pitch="0" yaw="0" mount_point="front_panel"/>
    <!-- RealSense Camera -->
    <!-- <xacro:include filename="../../../description/RealSenseD455.xacro" /> -->

    <!-- ROS2 CONTROL -->
    <xacro:include filename="ros2_control.xacro" />

</robot>