<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro"  name="robot">

    <!-- See common Gazebo pugins in the world file -->
    
    <!--
        To re-generate robot.urdf.generated.xml manually for troubleshooting:
          cd ~/robot_ws
          colcon build
          xacro install/articubot_one/share/articubot_one/robots/stingray/description/robot.urdf.xacro sim_mode:=false > src/articubot_one/robots/stingray/description/robot.urdf.generated.xml
    -->

    <xacro:include filename="../../../description/common_properties.xacro" />

    <xacro:include filename="robot_core.xacro" />

    <xacro:property name="imu_offset_x" value="${wheel_offset_x}"/>
    <xacro:property name="imu_offset_z" value="0.01"/>
    <xacro:include filename="../../../description/imu.xacro" />

    <xacro:include filename="../../../description/magnetometer.xacro" />

    <xacro:property name="laser_offset_x" value="${wheel_offset_x}"/>
    <xacro:property name="laser_offset_z" value="0.50"/>
    <xacro:include filename="../../../description/lidar.xacro" />

    <xacro:property name="gps_offset_x" value="${wheel_offset_x}"/>
    <xacro:property name="gps_offset_y" value="-0.16"/>
    <xacro:property name="gps_offset_z" value="0.45"/>
    <xacro:include filename="../../../description/gps.xacro" />

    <xacro:property name="camera_offset_x" value="${wheel_offset_x + 0.05}"/>
    <xacro:property name="camera_offset_z" value="0.45"/>
    <xacro:include filename="../../../description/camera.xacro" />

    <!-- xacro:include filename="../../../description/depth_camera.xacro" / -->
    <!-- xacro:include filename="../../../description/face.xacro" / -->
    
    <xacro:include filename="ros2_control.xacro" />

</robot>